apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec: 
  selector:
    matchLabels:
      app: conversaotemperatura
  template: 
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      containers:
      - name: conversaotemperatura
        image: mperes91/conversaotemperatura:v2

---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort